# xGitGuard Input Configurations
default:
  log_dir: None

github:
  throttle_time: 10
  # GitHub Public
  public_api_url: "https://api.github.com/search/code"
  public_commits_url: "https://api.github.com/repos/%s/%s/commits?path=%s"

  # GitHub Enterprise - For Open Source
  enterprise_api_url: "https://github.<< Enterprise Name >>.com/api/v3/search/code"
  enterprise_pre_url: "https://github.<< Enterprise Name >>.com/api/v3/repos/"
  url_validator: "https://github.<< Enterprise Name >>.com/api/v3/search/code"
  enterprise_commits_url: "https://github.<< Enterprise Name >>.com/api/v3/repos/{user_name}/{repo_name}/commits?path={file_path}"
  enterprise_header: { "Accept": "application/vnd.github.v3.raw" }

model:
  # Model Configurations

  # GitHub Public
  public:
    training_data_key: "public_key_train.csv"
    training_data_cred: "public_cred_train.csv"
    model_key_file: "public_xgg_key_rf_model_object.pickle"
    model_cred_file: "public_xgg_cred_rf_model_object.pickle"

  # GitHub Enterprise
  enterprise:
    training_data_key: "key_train.csv"
    training_data_cred: "cred_train.csv"
    model_key_file: "xgg_key_rf_model_object.pickle"
    model_cred_file: "xgg_cred_rf_model_object.pickle"

secrets:
  public_data_columns:
    [
      "Source",
      "Primary_Key",
      "Second_Key",
      "Extension",
      "URL",
      "Owner",
      "Repo_Name",
      "Commit_Details",
      "Secret",
      "Code",
      "Detected_Timestamp",
      "Key_Weight",
      "SKey_Count",
      "Entropy",
      "Dictionary_Similarity",
      "Score",
      "Year",
      "Month",
      "Day",
      "Hour",
    ]
  enterprise_data_columns:
    [
      "Source",
      "Second_Key",
      "Extension",
      "URL",
      "Owner",
      "Repo_Name",
      "Commit_Details",
      "Secret",
      "Code",
      "Detected_Timestamp",
      "Key_Weight",
      "SKey_Count",
      "Entropy",
      "Dictionary_Similarity",
      "Score",
      "Year",
      "Month",
      "Day",
      "Hour",
    ]
  enterprise_data_collector_columns:
    [
      "Source",
      "Second_Key",
      "Extension",
      "URL",
      "Owner",
      "Repo_Name",
      "Secret",
      "Code",
      "Detected_Timestamp",
      "Key_Weight",
      "SKey_Count",
      "Entropy",
      "Dictionary_Similarity",
      "Score",
      "Year",
      "Month",
      "Day",
      "Hour",
    ]
  public_data_collector_columns:
    [
      "Source",
      "Primary_Key",
      "Second_Key",
      "Extension",
      "URL",
      "Owner",
      "Repo_Name",
      "Secret",
      "Code",
      "Detected_Timestamp",
      "Key_Weight",
      "SKey_Count",
      "Entropy",
      "Dictionary_Similarity",
      "Score",
      "Year",
      "Month",
      "Day",
      "Hour",
    ]

file_scanner:
  local_file_scan_detection_columns:
    [
      "Source",
      "Second_Key",
      "Extension",
      "URL",
      "Secret",
      "Code",
      "Detected_Timestamp",
      "Key_Weight",
      "SKey_Count",
      "Entropy",
      "Dictionary_Similarity",
      "Score"
      "Year",
      "Month",
      "Day",
      "Hour",
    ]
  unique_columns: ["Source", "Second_Key", "Extension", "URL", "Code"]

keywords:
  public_data_columns:
    [
      "Source",
      "Second_Key",
      "URL",
      "Owner",
      "Repo_Name",
      "Commit_Details",
      "Detected_Timestamp",
      "Year",
      "Month",
      "Day",
      "Hour",
    ]
  enterprise_data_columns:
    [
      "Source",
      "Second_Key",
      "URL",
      "Owner",
      "Repo_Name",
      "Commit_Details",
      "Detected_Timestamp",
      "Year",
      "Month",
      "Day",
      "Hour",
    ]

